= Ethernet specification
:toc:
:toclevels: 4
:toc-position: left
:source-highlighter: pygments
:icons: font
:sectnums:

== TERMINOLOGY

* MAC        Media Access Control
* ARP        Address Resolution Protocol
* IP         Internet Protocol
* ICMP       Media Access Control
* VLAN       Virtual Local Area Network
* UDP        User Datagram protocol
* TCP        Transmission Control Protocol
* IPCP       Ip Command protocol
* IPLM       Ip link Mananger

== Ethernet protocol list

* Layer 2
** ARP
** VLAN
* Layer 3
** ICMP
* Layer 4
** UDP
** UDP socket
* Layer 5
** IPCP
** IPLM

== ARP

=== introduce

The Address Resolution Protocol (ARP) is a communication protocol used for
discovering the link layer address, such as a MAC address, associated with a
given internet layer address, typically an IPv4 address. This mapping is a
critical function in the Internet protocol suite.
ARP was defined in 1982 by RFC 826,which is Internet Standard STD 37.

=== Operating scope

The Address Resolution Protocol is a request-response protocol whose messages
are encapsulated by a link layer protocol. It is communicated within the
boundaries of a single network, never routed across internetworking nodes.
This property places ARP into the link layer of the Internet protocol suite

=== Message

* Arp request

* Internet Protocol (IPv4) over Ethernet ARP packet
