= 学习笔记
认真
:toc:
:toclevels: 4
:toc-position: left
:source-highlighter: pygments
:icons: font
:sectnums:

== 5-6学习内容

.今日学习计划
****

- [*] 学习shell中for/while 用法
- [*] 学习nc用法


****

.学习内容
....

<1> shell中可以使用修改IFS环境变量来避免空格，制表符，换行符被当作分隔符 +
方法：IFS=$'\n'
IFS.OLD=$IFS
IFS=$'\n'
IFS=$IFS.OLD

<2> server: nc -l -p 8880 > a.html  (server ip_addr:192.168.1.1)
client: cat a.html | nc 192.168.1.1 8880
....

== 5-9学习内容

* 配置mac的crontab服务

****
返回错误： crontab: “/usr/bin/vi” exited with status 1.
这是据说因为vi编辑的不行，vim却可以
执行 export EDITOR=vim 可以修正这个问题，或尝试 export EDITOR=nano.
查看成功的任务： crontab -l

****
== 5-10学习内容

=== 计划

- [*] shell学习之while用法学习
- [*] 总结

== 5-11学习内容

. 学习一个流量脚本
****
[source,shell]
#!/bin/bash

intervalo=1

info="/sys/class/net/"

cd $info

while [ 1 ]

do
    for interface in eth*

        do

          rx1=`cat $info$interface/statistics/rx_bytes`
          tx1=`cat $info$interface/statistics/tx_bytes`
          `sleep $((intervalo))` +
          rx2=`cat $info$interface/statistics/rx_bytes`
          tx2=`cat $info$interface/statistics/tx_bytes`
          echo $interface +
          echo ----
          echo RX: $((($rx2-$rx1)/($intervalo*1024))) Kbps
          echo TX: $((($tx2-$tx1)/($intervalo*1024))) Kbps
          done
done

****
== 5-12学习内容

* 学习ap打流工具
* 学习无线参数以及速率配置

== 5-13学习内容

.学习计划

****

. 通过设备获取MAC

[source,c]

int main(int argc, char *argv[])
{
    struct ifreq ifreq;
    int sock = 0;
    char mac[32] = "";

    if(argc < 2){
        printf("Usage: ./main eth0");
        return 1;

    }
    sock = socket(AF_INET,SOCK_STREAM,0);
    if(sock < 0)
    {
        perror("error sock");
        return 2;

    }
    strcpy(ifreq.ifr_name,argv[1]);
    if(ioctl(sock,SIOCGIFHWADDR,&ifreq) < 0)
    {
        perror("error ioctl");
        return 3;

   }
    int i = 0;
    for(i = 0; i < 6; i++){
        sprintf(mac+3*i, "%02X:", (unsigned char)ifreq.ifr_hwaddr.sa_data[i]);

    }
    mac[strlen(mac) - 1] = 0;
    printf("MAC: %s\n", mac);

    return 0;
}

****
.通过IP获取MAC

****
[source,c]
int main(int argc, char *argv[])
{
    struct sockaddr_in sin = { 0  };
    struct arpreq myarp = { { 0  }  };
    int sockfd;
    unsigned char *ptr;

    if(argc!=2) {
        printf("usage: %s <IP address>\n",argv[0]);
        exit(0);

    }
    sin.sin_family = AF_INET;
    if(inet_aton(argv[1], &sin.sin_addr)==0) {
        printf("%s: IP address '%s' not valid\n",argv[0],argv[1]);
        exit(0);

    }

    memcpy(&myarp.arp_pa, &sin, sizeof(myarp.arp_pa));
    strcpy(myarp.arp_dev, "eth0");
    if ((sockfd = socket(AF_INET, SOCK_DGRAM, 0)) == -1) {
        printf("%s: cannot open socket\n",argv[0]);
        exit(0);
    }

    if (ioctl(sockfd, SIOCGARP, &myarp) == -1) {
        printf("%s: no entry in arp_cache for '%s'\n",argv[0],argv[1]);
        exit(0);
    }
    ptr = &myarp.arp_ha.sa_data[0];
    printf("%s: MAC address for '%s' is : ",argv[0],argv[1]);
    printf("%x:%x:%x:%x:%x:%x\n",*ptr, *(ptr+1),*(ptr+2),*(ptr+3),*(ptr+4),*(ptr+5));

    return 1;
}

****

== 5-16学习计划

.今日学习

****
- [ ] shell学习
- [ ] Linux内核学习
****

== 5-20 Centos 配置smb
.一步一步
****
开启samba服务。
与 ubuntu 不同，Centos的安全级别默认高一些，需要关闭 SELINUX、iptables。 
[source,c]
[root@Gitlab-CI-Build0 ~]# cat /etc/selinux/config 

# This file controls the state of SELinux on the system. +
# SELINUX= can take one of these three values: +
#     enforcing - SELinux security policy is enforced. +
#     permissive - SELinux prints warnings instead of enforcing. +
#     disabled - No SELinux policy is loaded. +
SELINUX=disabled +
[root@Gitlab-CI-Build0 ~]# chkconfig --del iptables +
[root@Gitlab-CI-Build0 ~]# cat /etc/samba/smb.conf +
[homes]
comment = Home Directories +
browseable = yes +
writable = yes +
valid users = %S +
smbpasswd –a xxx +
chkconfig  smb on +
开启samba服务。 +
与 ubuntu 不同，Centos的安全级别默认高一些，需要关闭 SELINUX、iptables +
[root@Gitlab-CI-Build0 ~]# cat /etc/selinux/config  +

# This file controls the state of SELinux on the system. +
# SELINUX= can take one of these three values: +
#     enforcing - SELinux security policy is enforced. +
#     permissive - SELinux prints warnings instead of enforcing. +
#     disabled - No SELinux policy is loaded. +
SELINUX=disabled +
[root@Gitlab-CI-Build0 ~]# chkconfig --del iptables +
[root@Gitlab-CI-Build0 ~]# cat /etc/samba/smb.conf +
[homes] +
comment = Home Directories +
browseable = yes  +
writable = yes +
valid users = %S +
smbpasswd –a xxx +
chkconfig  *_smb_* on 

****

== 5-23 shell之用户输入

****
* shell 变量处理
** 可以输入$1,$2直到$9,超过九个可以用${10}

** $0可以打印出程序名字，但是会包含路径，去掉路径比较好的一个办法就是 +
用变量 _#basename#_  比如：
[source,shell]
name='basename $0'
echo $name

** shell中的变量 [red]#$*# 表示将所有的输入参数当作一个字符串,而#$@#是将变量按照空格识别
****

== 5-24文件输入输出

. 文件描述符 
+
,===
文件描述符,缩写,描述
0,STDIN,标准输入
1,STDOUT,标准输出
2,STDERR,标准错误
,===
+
. 使用#&>#来表示将错误信息和正常输出全部重定向到某一个地方去

. 未完待续 

== 5-25vim插件安装

NOTE: 注意事项

* 安装vim
* 同步github上的vim的配置
* git clone: link:https://github.com/VundleVim/Vundle.vim.git[git目录] ~/.vim/bundle/Vundle.vim 

* 安装ctags,cscope
* 完成配置

== 5-26 代码关系图工具doxygen

TIP: *doxygen* 是一个根据源码生成文档的工具，可以将代码中的调用关系生成表格 +
以及结构体中的关系调用等等。

.使用步骤
****
<1> 下载安装doxygen
<2> 在源码的根目录执行 *_doxygen -g_* 就会生成一个 *Doxygen* 的配置文件
<3> 安装工具 #graphviz# 目的是为了安装dot
<4> 开始配置配置文件
<5> 然后执行命令 [red]#doxygen# 即可
<6> 生成一个html文件夹中有所有函数调用关系
****







