= 学习笔记
认真
:toc:
:toclevels: 4
:toc-position: left
:source-highlighter: pygments
:icons: font
:sectnums:

== 5-6学习内容

.今日学习计划
****

- [*] 学习shell中for/while 用法
- [*] 学习nc用法


****

.学习内容
....

<1> shell中可以使用修改IFS环境变量来避免空格，制表符，换行符被当作分隔符 +
方法：IFS=$'\n'
IFS.OLD=$IFS
IFS=$'\n'
IFS=$IFS.OLD

<2> server: nc -l -p 8880 > a.html  (server ip_addr:192.168.1.1)
client: cat a.html | nc 192.168.1.1 8880
....

== 5-9学习内容

* 配置mac的crontab服务

****
返回错误： crontab: “/usr/bin/vi” exited with status 1.
这是据说因为vi编辑的不行，vim却可以
执行 export EDITOR=vim 可以修正这个问题，或尝试 export EDITOR=nano.
查看成功的任务： crontab -l

****
== 5-10学习内容

=== 计划

- [*] shell学习之while用法学习
- [*] 总结

== 5-11学习内容

. 学习一个流量脚本
****
[source,shell]
#!/bin/bash

intervalo=1

info="/sys/class/net/"

cd $info

while [ 1 ]

do
    for interface in eth*

        do

          rx1=`cat $info$interface/statistics/rx_bytes`
          tx1=`cat $info$interface/statistics/tx_bytes`
          `sleep $((intervalo))` +
          rx2=`cat $info$interface/statistics/rx_bytes`
          tx2=`cat $info$interface/statistics/tx_bytes`
          echo $interface +
          echo ----
          echo RX: $((($rx2-$rx1)/($intervalo*1024))) Kbps
          echo TX: $((($tx2-$tx1)/($intervalo*1024))) Kbps
          done
done

****

