= 软件资源和系统资源
认真
:toc:
:toclevels: 4
:toc-position: left
:source-highlighter: pygments
:icons: font
:sectnums:

== 鼠标键盘共享软件

.synergy
****
* MAC版本:

** link:http://synergy-project.org/files/nightly/synergy-v1.8.1-stable-257ac01-MacOSX1011-x86_64.dmg[MAC版本]

* Windows版本：

** link:http://synergy-project.org/files/nightly/synergy-v1.8.1-stable-257ac01-Windows-x86.msi[WIN32位]

** link:http://synergy-project.org/files/nightly/synergy-v1.8.1-stable-257ac01-Windows-x64.msi[WIN64位]

* Centos版本：

** link:http://synergy-project.org/files/nightly/synergy-v1.8.1-stable-257ac01-Linux-i686.rpm[Centos32位]

** link:http://synergy-project.org/files/nightly/synergy-v1.8.1-stable-257ac01-Linux-x86_64.rpm[64位]

* Ubuntu版本：

** link:http://synergy-project.org/files/nightly/synergy-v1.8.1-stable-257ac01-Linux-i686.deb[32位]

** link:http://synergy-project.org/files/nightly/synergy-v1.8.1-stable-257ac01-Linux-x86_64.deb[64位]

****
== CENTOS安装桌面

.need by

****
yum groupinstall -y "Desktop" "Desktop Platform" "Desktop Platform Development"　 "Fonts" 　"General Purpose Desktop"　 "Graphical Administration Tools"　 "Graphics Creation Tools" 　"Input Methods" 　"X Window System" 　"Chinese Support [zh]"　"Internet Browser"

****

== centos自动编译环境构建

.编译html文件

****
PATH=/home/hdd/.rvm/gems/ruby-2.2.1/bin:/home/hdd/.rvm/gems/ruby-2.2.1@global/bin:/home/hdd/.rvm/rubies/ruby-2.2.1/bin:/usr/lib/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/hdd/bin:/home/hdd/.rvm/bin

GEM_PATH=/home/hdd/.rvm/gems/ruby-2.2.1:/home/hdd/.rvm/gems/ruby-2.2.1@global

*/1 * * * * /home/hdd/my_importent/my_git_update.sh

****
== 免费GIT库资源
* 各种资源大全
* http://repo.or.cz/

== 构建asciidoctor环境基础
=== 编译环境

以在 _CentOS_ 上安装为例：

==== 安装 _Ruby_ 环境

[source,bash,linenums]
----
# gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
# \curl -sSL https://get.rvm.io | bash -s stable --ruby
----
==== 安装 _asciidoctor_

[source,bash,linenums]
----
# gem install asciidoctor # <1>
# gem install asciidoctor-diagram && yum install java-openjdk graphviz # <2>
# gem install asciidoctor-pdf-cjk asciidoctor-pdf-cjk-kai_gen_gothic asciidoctor-pdf-cjk-kaigen-gothic-kr && asciidoctor-pdf-cjk-kai_gen_gothic-install # <3>
----

<1> 安装 _asciidoctor_ 基本功能，支持导出 html5
<2> 安装 http://asciidoctor.org/docs/asciidoctor-diagram[asciidoctor-diagram] 扩展，支持文档内嵌入 _plantuml_、 _diaa_、 _Graphviz_、 _Shaape_
<3> 安装 _PDF_ 扩展，支持 _PDF_ 输出

==== 使用 _asciidoctor_

语法说明请阅读 http://asciidoctor.org/docs/asciidoc-syntax-quick-reference[AsciiDoc Syntax Quick Reference]

[source,bash,linenums]
----
# asciidoctor sample.adoc # <1>
# asciidoctor -r asciidoctor-diagram sample.adoc # <2>
# asciidoctor-pdf -r asciidoctor-diagram -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicCN sample.adoc # <3>
# asciidoctor -r asciidoctor-diagram -a data-uri sample.adoc # <4>
----

<1> 将 `sample.adoc` 输出为 `sample.html`
<2> 将 `sample.adoc` 输出为 `sample.html`，将 `sample.adoc` 中嵌入的 _plantuml_、 _diaa_ 转为为图片并插入 `sample.html`中
<3> 将 `sample.adoc` 输出为 `sample.pdf`
<4> 将 `sample.adoc` 输出为 `sample.html`，并将图片直接嵌入到 `sample.html`，这样不依赖外部图片文件

== 构建zsh环境

.如何安装zsh环境

TIP: 一定要首先安装 #zsh#

* yum install zsh
* git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

* cp ~/.zshrc ~/.zshrc.orig

* cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc

* chsh -s /bin/zsh
* 加载自己的zsh配置即可

NOTE:  遇到问题 #Could not resolve airline theme "solarized". Themes have been migrated to github.com/vim-airline/vim#
解决办法是，在 ～/.vimrc 中添加： #Plugin 'vim-airline/vim-airline-themes'#

== 远程构建ams云服务器

* 申请亚马逊云地址 https://aws.amazon.com/cn/
* install EC2
* install ubuntu

TIP: 安装完成后，就是一台远端的linux环境，公网地址可以使用。

* 原有的登陆方式比较麻烦，并且默认的用户名是ubuntu，还需要使用公钥，比较麻烦。
* 首先useradd 一个用户比如hdd 
* su hdd
* 生成ssh 公钥和私钥　id_rsd和id_rsa.pub文件
* 然后在亚马逊机器上，打开authorized_keys，添加需要登陆这台服务器的linux系统的公钥即可
* 也就是说，将本地机器的id_rsa.pub　复制到亚马逊机器的authorized_keys下
* 然后就可以通过hdd@52.197.239.60　登陆了

== 根据亚马逊云搭建VPN服务器

* wget https://git.io/vpnsetup -O vpnsetup.sh && sudo sh vpnsetup.sh
* VPN 教程在 github 上: https://github.com/hwdsl2/setup-ipsec-vpn
* 客户端地址: https://shadowsocks.org/en/download/clients.html

== 安装emacs

* sudo add-apt-repository -y ppa:ubuntu-elisp
* sudo apt-get update
* sudo apt-get install emacs-snapshot

== 配置shadowsocks　上谷歌

* aws服务端安装pip,apt-get install python-pip
* pip install shadowsocks
* 配置文件名为.json的配置文件
* 配置文件内容为

[source,python]

{
    "server":"0.0.0.0",
        "server_port":6666,
        "local_address": "127.0.0.1",
        "local_port":1080,
        "password":"12345678",
        "timeout":600,
        "method":"aes-256-cfb",
        "fast_open": true

}

* 客户端安装客户端软件地址为:https://shadowsocks.org/en/download/clients.html

* 配置客户端，打开设置-->网络设置-->代理配置-->配置代理路径为file:///etc/proxy.pac
* proxy.pac 文件在工程中
* 就可以了，大功告成。

== ubutu下安装英汉翻译词典

* 下载安装　　apt-get install startdic
* 下载词典库:link: https://www.oschina.net/news/36374/startdict-3-0-4
* 词典库地址: link:http://abloz.com/huzheng/stardict-dic/zh_CN/[词典库]
* 将词典解压到　/usr/share/startdic/dic中
* 打开划词开关即可
